//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace furniture_store.Database
{
    using System;
    using System.Collections.Generic;
    using System.Windows.Media;
    
    public partial class Products
    {
        public int id { get; set; }
        public string name { get; set; }
        public string category { get; set; }
        public Nullable<int> price { get; set; }
        public Nullable<int> total_count { get; set; }
        public Nullable<int> discount { get; set; }
        public string img { get; set; }

        public string ImgPath
        {
            get
            {
                return "/Resources/" + this.img;
            }
        }

        public string RriceWithDiscount
        {
            get
            {
                if (this.discount > 0)
                {
                    return "Со скидкой: " + Convert.ToString((1.0 - Convert.ToDouble(this.discount) / 100) * this.price);
                }
                else return "";
            }
        }

        public string PriceTextStyle
        {
            get
            {
                if (this.discount > 0) return "Strikethrough";
                else return "None";

            }
        }

        public SolidColorBrush ColorByDiscount
        {
            get
            {
                if(this.discount >= 15)
                {
                    return new SolidColorBrush(Color.FromRgb(38, 187, 172));
                }
                else { 
                    return new SolidColorBrush(Color.FromRgb(188, 251, 105));
                }
            }
        }
    }
}
